// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFEjHE04g7Lq9AKtpUYyrx9ooVdQ0RnxE',
    appId: '1:412449727396:web:e2a95731b170fa50e6d731',
    messagingSenderId: '412449727396',
    projectId: 'chatapp-dc049',
    authDomain: 'chatapp-dc049.firebaseapp.com',
    storageBucket: 'chatapp-dc049.appspot.com',
    measurementId: 'G-LHBF9X54RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBy6k4FIdm1Y24daOD0GD-XfkVplzxhnQ',
    appId: '1:412449727396:android:3ab67bee0596aba7e6d731',
    messagingSenderId: '412449727396',
    projectId: 'chatapp-dc049',
    storageBucket: 'chatapp-dc049.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX74w6xotFcK6tglCPxXDgHOu7zvGeD4k',
    appId: '1:412449727396:ios:47b1097c4d2276a2e6d731',
    messagingSenderId: '412449727396',
    projectId: 'chatapp-dc049',
    storageBucket: 'chatapp-dc049.appspot.com',
    iosClientId: '412449727396-hu23k15edris6ivj0k8e46n38vmtoprj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX74w6xotFcK6tglCPxXDgHOu7zvGeD4k',
    appId: '1:412449727396:ios:050a4be79d0de4a3e6d731',
    messagingSenderId: '412449727396',
    projectId: 'chatapp-dc049',
    storageBucket: 'chatapp-dc049.appspot.com',
    iosClientId: '412449727396-e1unuara5325kin3dcmj31he48eqj7kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
